{% set version = "6.0.2" %}

package:
  name: gspread
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gspread/gspread-{{ version }}.tar.gz
  sha256: 0982beeb07fa3ec4482a3aaa96ca13a1e6b427a0aca4058beab4cdc33c0cbb64

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - flit >=3.2,<4
  run:
    - python >=3.8
    - google-auth >=1.12.0
    - google-auth-oauthlib >=0.4.1
    - strenum == 0.4.15

test:
  imports:
    - gspread

about:
  home: https://github.com/burnash/gspread
  license: MIT
  license_file: LICENSE.txt
  summary: Google Spreadsheets Python API
  license_family: MIT
  dev_url: https://github.com/burnash/gspread
  doc_url: http://gspread.readthedocs.io/

extra:
  recipe-maintainers:
    - akashvyom
    - burnash
