{% set version = "6.1.0" %}

package:
  name: gspread
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gspread/gspread-{{ version }}.tar.gz
  sha256: 576b72b628b251d2ee41e02b982d3c714d511d2a5aa3a88e587ed9efc4d6e752

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - flit >=3.2,<4
  run:
    - python
    - google-auth >=1.12.0
    - google-auth-oauthlib >=0.4.1

test:
  imports:
    - gspread

about:
  home: https://github.com/burnash/gspread
  license: MIT
  license_file: LICENSE.txt
  summary: Google Spreadsheets Python API
  license_family: MIT
  dev_url: https://github.com/burnash/gspread
  doc_url: http://gspread.readthedocs.io/

extra:
  recipe-maintainers:
    - akashvyom
    - burnash
