{% set version = "5.12.4" %}

package:
  name: gspread
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gspread/gspread-{{ version }}.tar.gz
  sha256: 3fcef90183f15d3c9233b4caa021a83682f2b2ee678340c42d7ca7d8be98c6d1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - google-auth >=1.12.0
    - google-auth-oauthlib >=0.4.1

test:
  imports:
    - gspread

about:
  home: https://github.com/burnash/gspread
  license: MIT
  license_file: LICENSE.txt
  summary: Google Spreadsheets Python API
  license_family: MIT
  dev_url: https://github.com/burnash/gspread
  doc_url: http://gspread.readthedocs.io/

extra:
  recipe-maintainers:
    - akashvyom
    - burnash
